apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "env-injector.fullname" . }}-init
  labels:
    {{- include "env-injector.labels" . | nindent 4 }}
    shopstic.com/env-injector-controller: "true"
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-98"
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        {{- include "env-injector.labels" . | nindent 8 }}
        shopstic.com/env-injector-controller: "true"
    spec:
      serviceAccountName: {{ include "env-injector.fullname" . }}-init
      containers:
        - name: init
          image: "shopstic/k8s-env-injector-init:{{ .Chart.AppVersion }}"
          env:
            - name: ENV_INJECTOR_INIT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ENV_INJECTOR_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: ENV_INJECTOR_SECRET_NAME
              value: {{ include "env-injector.fullname" . }}-cert
          command:
            - bash
            - -c
            - |
              set -euo pipefail

              ENV_INJECTOR_MUTATING_WEBHOOK_CONFIGRATION_TEMPLATE=$(cat <<EOF
              {{- include "env-injector.mutatingWebhookConfiguration" . | nindent 14 }}
              EOF
              )
              {{ .Files.Get "scripts/init.sh" | nindent 14 }}
      restartPolicy: Never
      securityContext:
        runAsUser: 5000
        runAsGroup: 5000
