name: CI Workflow

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build-env:
    name: Build CI environment
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: chmod +r ~/.docker/config.json

      - name: Build and push shell Docker image
        uses: shopstic/buildkit-action@1.0.1
        with:
          context: ${{ github.workspace }}/shell
          image: shopstic/k8s-pod-annotator-ci
          tag: ${{ hashFiles('shell/*') }}
          skipIfExists: true

  build-app:
    name: Build applications
    needs: build-env
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Cache deno
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/.cache
          key: deno-${{ github.sha }}
          restore-keys: |
            deno-

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: chmod +r ~/.docker/config.json

      - name: Build
        env:
          IMAGE_NAME: shopstic/k8s-pod-annotator-ci
          IMAGE_TAG: ${{ hashFiles('shell/*') }}
          DENO_DIR: ${{ github.workspace }}/.cache/deno
        run: |-
          du -sh "${DENO_DIR}" || true
          ./cli.sh ci_build_in_shell

      - name: Build and push app Docker image
        uses: shopstic/buildkit-action@1.0.1
        with:
          context: ${{ github.workspace }}/build
          image: shopstic/k8s-pod-annotator
          tag: ${{ github.sha }}
