name: CI Workflow

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build-env:
    name: Build CI environment image
    runs-on: ubuntu-20.04
    outputs:
      image: ${{ steps.buildkit.outputs.image }}:${{ steps.buildkit.outputs.tag }}    
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - run: chmod +r ~/.docker/config.json

      - name: Build and push shell Docker image
        id: buildkit
        uses: shopstic/buildkit-action@1.0.10
        with:
          context: ${{ github.workspace }}/images/shell
          image: ghcr.io/shopstic/k8s-env-injector-ci
          tag: ${{ hashFiles('images/shell/*') }}
          skipIfExists: true

  build-app:
    name: Build app image
    needs: build-env
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Cache deno
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/.cache
          key: deno-${{ hashFiles('lock.json') }}
          restore-keys: |
            deno-${{ hashFiles('lock.json') }}
            
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: chmod +r ~/.docker/config.json

      - name: Build
        env:
          SHELL_IMAGE: ${{ needs.build-env.outputs.image }}
          DENO_DIR: ${{ github.workspace }}/.cache/deno
        run: |-
          if ls "${DENO_DIR}" > /dev/null 2>&1; then
            du -sh "${DENO_DIR}"
          fi

          cat <<EOF | docker run \
            --workdir /repo \
            -i \
            --rm \
            -v "${GITHUB_WORKSPACE}:/repo" \
            -v "${DENO_DIR}:/root/.cache/deno" \
            -e "DENO_DIR=/root/.cache/deno" \
            "${SHELL_IMAGE}" \
            bash -l
          set -euo pipefail

          ./cli.sh code_quality
          ./cli.sh test
          ./cli.sh test_helm_chart
          ./cli.sh compile
          EOF

      - name: Github ref name
        id: ref_name
        run: |
          if [[ "${GITHUB_REF}" =~ ^refs/heads/.* ]]; then
            echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
          fi

          if [[ "${GITHUB_REF}" =~ ^refs/tags/.* ]]; then
            echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
          fi

      - name: Build and push app Docker image latest
        uses: shopstic/buildkit-action@1.0.10
        if: steps.ref_name.outputs.branch == 'main'
        with:
          context: ${{ github.workspace }}/images/app
          image: shopstic/k8s-env-injector
          tag: ${{ github.sha }}
          additionalTags: latest
          skipIfExists: false

      - name: Build and push app Docker image to tag
        uses: shopstic/buildkit-action@1.0.10
        if: steps.ref_name.outputs.tag != ''
        with:
          context: ${{ github.workspace }}/images/app
          image: shopstic/k8s-env-injector
          tag: ${{ steps.ref_name.outputs.tag }}
          skipIfExists: false

      - name: Build and push init Docker image latest
        uses: shopstic/buildkit-action@1.0.10
        if: steps.ref_name.outputs.branch == 'main'
        with:
          context: ${{ github.workspace }}/images/init
          image: shopstic/k8s-env-injector-init
          tag: ${{ github.sha }}
          additionalTags: latest
          skipIfExists: false

      - name: Build and push init Docker image to tag
        uses: shopstic/buildkit-action@1.0.10
        if: steps.ref_name.outputs.tag != ''
        with:
          context: ${{ github.workspace }}/images/init
          image: shopstic/k8s-env-injector-init
          tag: ${{ steps.ref_name.outputs.tag }}
          skipIfExists: false

      - name: Build and push Helm Chart
        if: steps.ref_name.outputs.branch == 'main' || steps.ref_name.outputs.tag != ''
        env:
          SHELL_IMAGE: ${{ needs.build-env.outputs.image }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_TAG: ${{ steps.ref_name.outputs.tag }}
        run: |-
          cat <<EOF | docker run \
            --workdir /repo \
            -i \
            --rm \
            -e GITHUB_SHA \
            -e GITHUB_TAG \
            -v "${GITHUB_WORKSPACE}:/repo" \
            -v "${HOME}/.docker/config.json:/root/.docker/config.json" \
            "${SHELL_IMAGE}" \
            bash -l
          set -euo pipefail

          if [[ "${GITHUB_TAG}" != "" ]]; then
            ./cli.sh push_helm_chart "${GITHUB_TAG}"
          else
            ./cli.sh push_helm_chart "${GITHUB_SHA}"
          fi
          
          EOF