name: Dev

on: [push]

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: [self-hosted, nix]
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Test
        shell: nix develop -v -c bash {0}
        run: |-
          set -euo pipefail
          ./cli.sh code_quality
          ./cli.sh test
          ./cli.sh test_helm_chart

  build:
    name: Build image
    runs-on: [self-hosted, nix]
    needs: [test]
    env:
      IMAGE_REPOSITORY: public.ecr.aws/shopstic
    strategy:
      matrix:
        image: [app, init]
        arch: [x86_64, aarch64]
        include:
          - image: app
            imageName: k8s-env-injector
          - image: init
            imageName: k8s-env-injector-init
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Login to Amazon ECR
        uses: ./.github/actions/login-to-public-ecr
        with:
          imageRepo: ${{ env.IMAGE_REPOSITORY }}

      - name: Build container images
        run: |-
          nix build -L -v '.#packages.${{ matrix.arch }}-linux.${{ matrix.image }}Image'

      - name: Push
        env:
          GITHUB_SHA: ${{ github.sha }}
          NIX_ARCH: ${{ matrix.arch }}
          IMAGE_NAME: ${{ matrix.imageName }}
        shell: nix develop -v -c bash {0}
        run: |-
          IMAGE_ARCH="amd64"
          if [[ "${NIX_ARCH}" == "aarch64" ]]; then
            IMAGE_ARCH="arm64"
          fi

          IMAGE_TAG="dev-${IMAGE_ARCH}-${GITHUB_SHA}"

          skopeo --insecure-policy copy \
            docker-archive:./result \
            docker://"${IMAGE_REPOSITORY}"/"${IMAGE_NAME}":"${IMAGE_TAG}"

  push-multi-arch:
    name: Push multi-arch image manifest
    runs-on: [self-hosted, nix]
    needs: [build]
    env:
      IMAGE_REPOSITORY: public.ecr.aws/shopstic
    strategy:
      matrix:
        image: [app, init]
        include:
          - image: app
            imageName: k8s-env-injector
          - image: init
            imageName: k8s-env-injector-init      
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Login to Amazon ECR
        uses: ./.github/actions/login-to-public-ecr
        with:
          imageRepo: ${{ env.IMAGE_REPOSITORY }}

      - name: Push multi-arch manifest
        shell: nix develop -v -c bash {0}
        env:
          GITHUB_SHA: ${{ github.sha }}
          IMAGE_NAME: ${{ matrix.imageName }}
        run: |-
          manifest-tool push from-args \
            --platforms linux/amd64,linux/arm64 \
            --template "${IMAGE_REPOSITORY}"/"${IMAGE_NAME}":dev-ARCH-"${GITHUB_SHA}" \
            --target "${IMAGE_REPOSITORY}"/"${IMAGE_NAME}":dev-"${GITHUB_SHA}"

  push-helm-chart:
    name: Push Helm chart
    runs-on: [self-hosted, nix]
    needs: [build]
    env:
      IMAGE_REPOSITORY: public.ecr.aws/shopstic   
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Login to Amazon ECR
        uses: ./.github/actions/login-to-public-ecr
        with:
          imageRepo: ${{ env.IMAGE_REPOSITORY }}

      - name: Push Helm chart
        shell: nix develop -v -c bash {0}
        env:
          HELM_CHART_VERSION: 1.0.0-${{ github.sha }}
          HELM_APP_VERSION: dev-${{ github.sha }}
        run: |-
          ./cli.sh push_helm_chart \
            "${HELM_CHART_VERSION}" \
            "${HELM_APP_VERSION}" \
            "oci://${IMAGE_REPOSITORY}/charts"